// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/passport-photo-generator": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/passport-photo-generator";
  };
  "routes/passport-photo-generator._index.tsx": {
    id: "routes/passport-photo-generator._index";
    page: "/passport-photo-generator";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/passport-photo-generator._index": typeof import("./src/routes/passport-photo-generator._index.tsx");
  "routes/_index": typeof import("./src/routes/_index.tsx");
};